# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_tapLock_wrappers", use_symbols = TRUE, package_name = "tapLock")

#' @usage NULL
#' @useDynLib tapLock, .registration = TRUE
NULL

#' @title Parse cookies
#' @description Parses cookies from a string
#'
#' @param x A string containing the cookies
#'
#' @return A list containing the cookies
#' @keywords internal
parse_cookies <- function(cookies) .Call(wrap__parse_cookies, cookies)

Claims <- new.env(parent = emptyenv())

Claims$print <- function() invisible(.Call(wrap__Claims__print, self))

#' @export
`$.Claims` <- function (self, name) { func <- Claims[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Claims` <- `$.Claims`

JwksManager <- new.env(parent = emptyenv())

JwksManager$new <- function(url) .Call(wrap__JwksManager__new, url)

JwksManager$decode_token <- function(token) .Call(wrap__JwksManager__decode_token, self, token)

#' @export
`$.JwksManager` <- function (self, name) { func <- JwksManager[[name]]; environment(func) <- environment(); func }

#' @export
`[[.JwksManager` <- `$.JwksManager`


# nolint end
