on:
  pull_request:
    branches:
      - main

name: Unit testing

jobs:
  r_cmd_check:
    name: R CMD check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check
    - uses: r-lib/actions/check-r-package@v2
      with:
        error-on: '"error"'
  r_cmd_check_as_cran:
    name: R CMD check as CRAN
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check
    - uses: r-lib/actions/check-r-package@v2
      with:
        args: 'c("--no-manual", "--as-cran")'
        error-on: '"error"'
        check-dir: '"check"'
  test_build_pkgdown:
    name: Test build pkgdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site(new_process = FALSE, install = FALSE)
        shell: Rscript {0}
